CREATE TYPE tipo_notificacion AS ENUM (
    'nueva_nota',
    'nueva_falta',
    'nueva_observacion',
    'nuevo_mensaje',
    'nuevo_aviso',
    'recordatorio_material'
);

CREATE TABLE usuarios (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(200) NOT NULL,
    telefono VARCHAR(20),
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('tutor','profesor','admin')),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alumnos (
    alumno_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(200) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    foto_url VARCHAR(500)
);

CREATE TABLE profesores (
    user_id INTEGER PRIMARY KEY,
    departamento VARCHAR(100) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES usuarios(user_id) ON DELETE CASCADE
);

CREATE TABLE tutores_legales (
    user_id INTEGER PRIMARY KEY,
    es_alumno BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES usuarios(user_id) ON DELETE CASCADE
);

CREATE TABLE cursos (
    curso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    anio_academico VARCHAR(9) NOT NULL
);

CREATE TABLE asignaturas (
    asignatura_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL
);

CREATE TABLE curso_asignatura (
    curso_asignatura_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id INTEGER NOT NULL,
    asignatura_id INTEGER NOT NULL,
    UNIQUE (curso_id, asignatura_id),
    FOREIGN KEY (curso_id) REFERENCES cursos(curso_id) ON DELETE CASCADE,
    FOREIGN KEY (asignatura_id) REFERENCES asignaturas(asignatura_id) ON DELETE CASCADE
);

CREATE TABLE alumno_curso (
    alumno_id INTEGER NOT NULL,
    curso_id INTEGER NOT NULL,
    PRIMARY KEY (alumno_id, curso_id),
    FOREIGN KEY (alumno_id) REFERENCES alumnos(alumno_id) ON DELETE CASCADE,
    FOREIGN KEY (curso_id) REFERENCES cursos(curso_id) ON DELETE CASCADE
);

CREATE TABLE notas (
    nota_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id INTEGER NOT NULL,
    curso_asignatura_id INTEGER NOT NULL,
    trimestre INTEGER NOT NULL CHECK (trimestre BETWEEN 1 AND 3),
    calificacion NUMERIC(4,2) CHECK (calificacion BETWEEN 0 AND 10),
    fecha_registro DATE DEFAULT CURRENT_DATE,
    UNIQUE (alumno_id, curso_asignatura_id, trimestre),
    FOREIGN KEY (alumno_id) REFERENCES alumnos(alumno_id) ON DELETE CASCADE,
    FOREIGN KEY (curso_asignatura_id) REFERENCES curso_asignatura(curso_asignatura_id) ON DELETE CASCADE
);

CREATE TABLE faltas (
    falta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id INTEGER,
    fecha DATE DEFAULT CURRENT_DATE NOT NULL,
    hora TIME,
    FOREIGN KEY (alumno_id) REFERENCES alumnos(alumno_id) ON DELETE CASCADE
);

CREATE TABLE observaciones (
    observacion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id INTEGER NOT NULL,
    asignatura_id INTEGER,
    trimestre INTEGER CHECK (trimestre BETWEEN 1 AND 3),
    mensaje TEXT NOT NULL,
    profesor_id INTEGER,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (alumno_id) REFERENCES alumnos(alumno_id) ON DELETE CASCADE,
    FOREIGN KEY (asignatura_id) REFERENCES asignaturas(asignatura_id) ON DELETE SET NULL,
    FOREIGN KEY (profesor_id) REFERENCES profesores(user_id) ON DELETE SET NULL
);

CREATE TABLE chats (
    chat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(20) DEFAULT 'individual' CHECK (tipo IN ('individual','grupal')),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_chat (
    user_id INTEGER NOT NULL,
    chat_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, chat_id),
    FOREIGN KEY (user_id) REFERENCES usuarios(user_id) ON DELETE CASCADE,
    FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE
);

CREATE TABLE mensajes (
    mensaje_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER,
    user_id INTEGER,
    texto TEXT NOT NULL,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES usuarios(user_id) ON DELETE CASCADE
);

CREATE TABLE avisos (
    aviso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    mensaje TEXT NOT NULL,
    es_importante BOOLEAN DEFAULT FALSE,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE material_escolar (
    material_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    editorial VARCHAR(200),
    isbn VARCHAR(20)
);

CREATE TABLE curso_material (
    curso_id INTEGER NOT NULL,
    material_id INTEGER NOT NULL,
    PRIMARY KEY (curso_id, material_id),
    FOREIGN KEY (curso_id) REFERENCES cursos(curso_id) ON DELETE CASCADE,
    FOREIGN KEY (material_id) REFERENCES material_escolar(material_id) ON DELETE CASCADE
);

CREATE TABLE notificaciones (
    notificacion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    tipo tipo_notificacion NOT NULL,
    mensaje VARCHAR(200) NOT NULL,
    entidad_id INTEGER,
    entidad_tipo VARCHAR(30),
    leida BOOLEAN DEFAULT FALSE,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES usuarios(user_id) ON DELETE CASCADE
);

CREATE TABLE tutor_alumno (
    tutor_id INTEGER NOT NULL,
    alumno_id INTEGER NOT NULL,
    parentesco VARCHAR(50),
    PRIMARY KEY (tutor_id, alumno_id),
    FOREIGN KEY (tutor_id) REFERENCES tutores_legales(user_id) ON DELETE CASCADE,
    FOREIGN KEY (alumno_id) REFERENCES alumnos(alumno_id) ON DELETE CASCADE
);

CREATE TABLE profesor_asignatura (
    profesor_id INTEGER NOT NULL,
    asignatura_id INTEGER NOT NULL,
    PRIMARY KEY (profesor_id, asignatura_id),
    FOREIGN KEY (profesor_id) REFERENCES profesores(user_id) ON DELETE CASCADE,
    FOREIGN KEY (asignatura_id) REFERENCES asignaturas(asignatura_id) ON DELETE CASCADE
);